# Production BaseURL
baseURL = "https://pgjdbc.github.io/pgjdbc/"
languageCode = "en-us"
title = "Pgjdbc"
[permalinks]
page = "/:slug/"
posts = "/:year/:month/:slug/"

# Search index for lunr.js
[outputFormats.SearchIndex]
baseName = "search"
mediaType = "application/json"

[outputs]
home = ["HTML", "RSS", "SearchIndex"]
# section = ["HTML", "RSS", "SearchIndex"]
page = ["HTML"]
