name: Seed build cache

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - 'appveyor.xml'

permissions:
  contents: read

concurrency:
  # Push to the same branch (ref is like refs/heads/release) should stop previous buildcache
  # workflows for the branch.
  # More info: https://stackoverflow.com/a/68422069/253468
  group: ci-buildcache-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_secrets:
    name: Check if required secrets are available
    runs-on: ubuntu-latest
    env:
      S3_BUILD_CACHE_ACCESS_KEY_ID: ${{ secrets.S3_BUILD_CACHE_ACCESS_KEY_ID }}
      S3_BUILD_CACHE_SECRET_KEY: ${{ secrets.S3_BUILD_CACHE_SECRET_KEY }}
    outputs:
      secrets_available: ${{ steps.set-matrix.outputs.secrets_available }}
    steps:
      - id: set-matrix
        run: |
          if [[ -n "${S3_BUILD_CACHE_ACCESS_KEY_ID:-}" ]] && [[ -n "${S3_BUILD_CACHE_SECRET_KEY:-}" ]]; then
            echo "secrets_available=true" >> $GITHUB_OUTPUT
          else
            echo "secrets_available=false" >> $GITHUB_OUTPUT
          fi

  seed-build-cache:
    needs: check_secrets
    if: ${{ needs.check_secrets.outputs.secrets_available == 'true' }}
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        jdk: [21]

    name: '${{ matrix.os }}, ${{ matrix.jdk }} seed build cache'
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 50
      - name: 'Set up JDK ${{ matrix.jdk }}'
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4
        with:
          java-version: ${{ matrix.jdk }}
          distribution: liberica
      - uses: burrunan/gradle-cache-action@663fbad34e03c8f12b27f4999ac46e3d90f87eca # v3
        name: Build pgjdbc
        env:
          S3_BUILD_CACHE_ACCESS_KEY_ID: ${{ secrets.S3_BUILD_CACHE_ACCESS_KEY_ID }}
          S3_BUILD_CACHE_SECRET_KEY: ${{ secrets.S3_BUILD_CACHE_SECRET_KEY }}
        with:
          job-id: jdk${{ matrix.jdk }}
          arguments: build -x test --scan -i
