name: Seed build cache

on:
  push:
    branches:
      - '**'

jobs:
  ubuntu-code-style:
    if: github.repository == 'pgjdbc/pgjdbc'
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        jdk: [8, 11]

    name: '${{ matrix.os }}, ${{ matrix.jdk }} seed build cache'
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 50
      - name: 'Set up JDK ${{ matrix.jdk }}'
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - uses: burrunan/gradle-cache-action@v3
        name: Build pgjdbc
        env:
          S3_BUILD_CACHE_ACCESS_KEY_ID: ${{ secrets.S3_BUILD_CACHE_ACCESS_KEY_ID }}
          S3_BUILD_CACHE_SECRET_KEY: ${{ secrets.S3_BUILD_CACHE_SECRET_KEY }}
        with:
          job-id: jdk${{ matrix.jdk }}
          arguments: build -x test --scan -i
