name: Test Debezium

# only on push or allow us to do this manually using workflow dispatch
on: [workflow_dispatch]

permissions:
  contents: read

jobs:
  snapshot:
    name: Debezium
    runs-on: ubuntu-22.04
    #only for master
    if: ${{ github.ref == 'refs/heads/master' }}
    env:
      ACTIONS_STEP_DEBUG: true
      ACTIONS_RUNNER_DEBUG: true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 50
      - name: 'Set up JDK 17'
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
      - uses: burrunan/gradle-cache-action@v1
        name: Publish Snapshot
        with:
          job-id: jdk8
          arguments: postgresql:publishToMavenLocal -Ppgjdbc.version=1.0.0-dev-master -PskipJavadoc
      - name: clone debezium and run tests
        run: |
          git clone --depth 1 https://github.com/debezium/debezium.git
          cd debezium
          mvn clean verify -pl :debezium-connector-postgres -am -Dversion.postgres.server=14 -Dversion.postgresql.driver=1.0.0-dev-master-SNAPSHOT
